name: npm install test

on:
  push:
    branches: [master]

jobs:
  test-linux:
    name: Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js et npm
        run: |
          sudo apt update
          sudo apt install nodejs
          sudo apt install npm
          node -v
          npm -v

      - name: Install ts-node and typescript globally
        run: |
          sudo apt install ts-node
          ts-node -v

      - name: Install deps
        run: npm i

      - name: Tests
        run: npm test

      - name: ts-node
        run: ts-node src/main.ts "6+2*(10/5)" "2+2" "8-5^2"

  test-macos:
    name: macOS
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Verify versions Node.js npm
        run: |
          node -v
          npm -v

      - name: Install ts-node and typescript globally
        run: |
          npm install -g ts-node typescript
          ts-node -v

      - name: Install deps
        run: npm i

      - name: Tests
        run: npm test

      - name: ts-node
        run: ts-node src/main.ts "6+2*(10/5)" "2+2" "8-5^2"
