name: Test ts-node sur Linux et macOS

on:
  push:
    branches: [master]

jobs:
  test-linux:
    name: Test sur Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Installer Node.js et npm
        run: |
          sudo apt update
          sudo apt install nodejs
          sudo apt install npm
          node -v
          npm -v

      - name: Installer ts-node et typescript globalement
        run: |
          sudo apt install ts-node
          ts-node -v

      - name: Installer les dépendances du projet
        run: npm i

      - name: Tests
        run: npm test

      - name: Exécuter ts-node avec des expressions
        run: ts-node src/main.ts "6+2*(10/5)" "2+2" "8-5^2"

  test-macos:
    name: Test sur macOS
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Installation de Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Vérifier les versions Node.js et npm
        run: |
          node -v
          npm -v

      - name: Installer ts-node et typescript globalement
        run: |
          npm install -g ts-node typescript
          ts-node -v

      - name: Installer les dépendances du projet
        run: npm i

      - name: Tests
        run: npm test

      - name: Exécuter ts-node avec des expressions
        run: ts-node src/main.ts "6+2*(10/5)" "2+2" "8-5^2"
